app/routes.py
from flask import render_template, redirect, url_for, Blueprint, request, jsonify
from .forms import LoginForm, RegistrationForm, PostForm
from flask_login import login_required, current_user, logout_user
from flask_jwt_extended import jwt_required, unset_jwt_cookies
from .functions import *
from . import jwt_manager


#   ---------------------- 
#         Blueprints
#   ----------------------

main = Blueprint('main', __name__)
auth = Blueprint('auth', __name__)
profile = Blueprint('profile', __name__)
posts = Blueprint('posts', __name__)
admin = Blueprint('admin', __name__)

#   ---------------------- 
#       Error handlers
#   ----------------------

@jwt_manager.unauthorized_loader
def custom_unauthorized_response_jwt(_err):
    '''
    Обработчик ошибок, связанных с отсутствием JWT токена
    '''
    return redirect(url_for('auth.register', next=request.url))

@main.app_errorhandler(405)
def handle_405_error(_err):
    '''
    Обработчик ошибок HTTP 405
    '''
    return redirect(url_for('main.index'))

@main.app_errorhandler(404)
def handle_404_error(_err):
    '''
    Обработчик ошибок HTTP 404
    '''
    return render_template('404.html')
#   ----------------------
#           Pages
#   ----------------------

@main.route('/')
def index():
    '''
    Функция для рендера главной страницы
    '''
    return render_template('index.html')

@posts.route('/popular')
def popular():
    '''
    Функция для рендера страницы с постами
    '''
    return render_template('popular.html', form=PostForm(), posts=get_posts())

@main.route('/about')
def about():
    '''
    Функция для рендера страницы "About"
    '''
    return render_template('about.html')

#   ----------------------
#          Posts
#   ----------------------

@posts.route('/add-post', methods=["GET", "POST"])
def add_post():
    '''
    Функция для добавления постов.
    '''
    if request.method == "GET":
        '''
        Если запрос был отправлен методом GET, т. е. пользователь нажал на кнопку "Create" в шапке сайта,
        рендерится страница с добавлением поста.
        '''
        if not current_user.is_authenticated:
            '''
            Если пользователь не авторизован, перенаправить на страницу регистрации
            '''
            return redirect(url_for('auth.register'))
        return render_template('addpost.html', form=PostForm())
    else:
        form = PostForm()
        return post_add(form, current_user)

@posts.route('/delete-post', methods=["DELETE"])
def delete_post():
    '''
    Функция удаления поста.
    '''
    post_id = request.json['id']
    if not post_id:
        '''
        Если в запросе не был отправлен id поста, отправить ошибку.
        '''
        return {"message": "Post not found."}, 404
    post = Post.query.get(post_id)
    if post:
        '''
        Если есть пост с данным id, удалить его из БД
        '''
        db.session.delete(post)
        db.session.commit()
        return {"message": "Post deleted"}, 200
    '''
    Если нету, отправить ошибку
    '''
    return {"message": "Post not found"}, 400

@posts.route('/edit-post', methods=["POST"])
def edit_post():
    '''
    Функция для обновления поста в БД
    '''
    content, post_id = request.json['content'], request.json['id']
    if not content or not post_id:
        '''
        Если в запросе не был отправлен id поста, отправить ошибку.
        '''
        return {"message": "Missing data."}
    post = Post.query.get(post_id)
    if post:
        '''
        Если такой пост существует, обновить его информацию.
        '''
        post.content = content
        db.session.commit()
        return {"message": "Post edited"}, 200 
    '''
    Если нету, отправить ошибку.
    '''
    return {"message": "Post not found"}, 400

@posts.route('/add-like', methods=["POST"])
def add_like():
    '''
    Функция для добавления лайка.
    '''
    data = request.get_json()
    if not data or 'user' not in data or 'post' not in data:
        '''
        Если в запросе не корректно была отправлена информация, отправить ошибку.
        '''
        return jsonify({"error": "Invalid JSON data"}), 400

    user_id, post_id = data['user'], data['post']
    user = User.query.get(user_id)
    post = Post.query.get(post_id)

    if not user or not post:
        '''
        Если нет пользователя и поста по данным id, то отправить ошибку.
        '''
        return jsonify({"error": "User or post not found"}), 404

    if post not in user.liked_posts:
        '''
        Если пользователь ранее не лайкал пост, добавить его лайк.
        '''
        user.liked_posts.append(post)
        db.session.commit()
        return jsonify({"msg": "Like added"}), 200
    '''
    Если лайкал, отправить ошибку
    '''
    return jsonify({"msg": "Already liked"}), 400

@posts.route('/delete-like', methods=["POST"])
def delete_like():
    '''
    Функция удаления лайка
    '''
    data = request.get_json()
    if not data or 'user' not in data or 'post' not in data:
        '''
        Если в запросе не корректно была отправлена информация, отправить ошибку.
        '''
        return jsonify({"error": "Invalid JSON data"}), 400

    user_id, post_id = data['user'], data['post']
    user = User.query.get(user_id)
    post = Post.query.get(post_id)

    if not user or not post:
        '''
        Если нет пользователя и поста по данным id, то отправить ошибку.
        '''
        return jsonify({"error": "User or post not found"}), 404

    if post in user.liked_posts:
        '''
        Если пользователь ранее лайкал пост, удалить его лайк.
        '''
        user.liked_posts.remove(post)
        db.session.commit()
        return jsonify({"msg": "Like removed"}), 200
    '''
    Если не лайкал, отправить ошибку.
    '''
    return jsonify({"msg": "Like not found"}), 400


#   ----------------------
#       Authentication
#   ----------------------

@auth.route('/login', methods=["POST", "GET"])
def login():
    '''
    Функция входа в аккаунт
    '''
    if current_user.is_authenticated:
        '''
        Если пользователь уже авторизован, перенаправить его на другую страницу.
        '''
        next_page = request.args.get('next')
        return redirect(next_page or url_for('profile.user'))
    form = LoginForm()
    if form.validate_on_submit():
        '''
        Валидация данных.
        '''
        return validate_login(form)
    '''
    Рендер страницы
    '''
    return render_template('login.html', form=form)


@auth.route('/register', methods=["POST", "GET"])
def register():
    '''
    Функция регистрации
    '''
    if current_user.is_authenticated:
        '''
        Если пользователь уже авторизован, перенаправить его на другую страницу.
        '''
        next_page = request.args.get('next')
        return redirect(next_page or url_for('profile.user'))
    form = RegistrationForm()
    if form.validate_on_submit():
        '''
        Валидация данных
        '''
        return validate_registration(form)
    '''
    Рендер страницы.
    '''
    return render_template('registrate.html', form=form)

#   ----------------------
#        User profile
#   ----------------------

@profile.route('/confirm-edit', methods=["POST"])
def confirm_edit():
    '''
    Функция изменения данных пользователя
    '''
    return change_info(request)

@profile.route('/change-avatar', methods=["POST"])
def change_av():
    '''
    Функция изменения картинки профилья пользователя.
    '''
    return change_avatar(request)

@profile.route('/logout', methods=["POST"])
def logout():
    '''
    Функция выхода из аккаунта
    '''
    response = make_response(jsonify({"message": "Logged out"}))
    unset_jwt_cookies(response)
    logout_user()
    return response, 200

@profile.route('/user')
@login_required
@jwt_required()
def user():
    '''
    Рендер профиля пользователя
    '''
    return render_template('user-profile.html')

app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arteria: About</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/about.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='styles/images/arteria-logo.png') }}">
    
</head>
<body>
    {% include "header.html" %}
    <h1 id="welcome">Добро пожаловать на Arteria – место, где мысли текут свободно!</h1>
    <div id="content">
        <div>
            <div>
                <p class="questions">Что такое Arteria?</p>
                <p class="answer">Arteria – это онлайн-платформа, созданная для тех, кто ценит глубокие размышления, аналитику и разнообразие тем. Мы стремимся стать вашим проводником в мир идей, знаний и открытий.</p>
            </div>
            <div>
                <p class="questions">Наша миссия</p>
                <p class="answer">Наша цель – вдохновлять вас новыми идеями, помогать находить ответы на сложные вопросы и расширять горизонты вашего мышления. Мы верим, что каждый человек уникален, и наша задача – предоставить вам пространство для интеллектуального роста и самовыражения.</p>
            </div>
            <div id="list">
                <div>
                    <p class="not-list">Чем мы занимаемся?</p>
                <p class="not-list">На нашем сайте вы найдете:</p>
                </div>
                
                <ul class="answer">
                    <li>
                        <b>Аналитические статьи:</b> Глубокие исследования актуальных вопросов, которые помогут вам лучше понять окружающий мир.
                    </li>
                    <li>
                        <b>Интервью и беседы:</b> Интересные разговоры с экспертами и интересными личностями.
                    </li>
                    <li>
                        <b>Рекомендации книг и фильмов:</b> Подборки материалов, которые стоит прочитать или посмотреть.
                    </li>
                </ul>
                <p>Мы постоянно обновляем контент, чтобы у вас всегда было что-то новое и интересное для чтения.</p>
            </div>
            <div>
                <p class="questions">Кто мы?</p>
                <p class="answer">Команда <i><b>Arteria</b></i> состоит из увлеченных людей, которые любят делиться своими знаниями и опытом. Наши авторы – это профессионалы в своих областях, готовые предложить свежий взгляд на привычные вещи.</p>
            </div>
            <div>
                <p class="questions">Присоединяйтесь к нам!</p>
                <p class="answer">Спасибо за то, что выбрали Arteria. Пусть ваши мысли будут свободными и яркими!</p>
            </div>
        </div>
        <div>
            <h2 class="questions">Над проектом работали:</h2>
            <ul>
                <li><a href="https://github.com/feredeyz"><b><i>feredeyz</i></b></a> - автор идеи, техническая часть проекта</li>
                <li><i><a href="https://github.com/Shukuch1">sanechka_doter</a></i> - дизайнер</li>
            </ul>
        </div>
    </div>
        
</body>
</html>

app/templates/addpost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arteria: Add Post</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/addpost.css')}}">
    <meta name="author" content="feredeyz">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='styles/images/arteria-logo.png') }}">
</head>
<body>
    {% include "header.html" %}
    <div id="addpost">
        <form action="/add-post" method="post">
            {{ form.hidden_tag() }}
            {{ form.title.label }} {{ form.title() }} <br>
            {{ form.content.label }} {{ form.content() }} <br>
            {{ form.submit() }}
        </form>
    </div>

    <script src="{{ url_for('static', filename='js/addPost.js') }}"></script>
</body>
</html>

app/templates/header.html
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/header.css') }}">
</head>
<header>
    <div id="header">
        <a href="{{ url_for('main.index') }}">
            <img id="logo" src="{{ url_for('static', filename='styles/images/arteria-logo.png') }}" alt="logo">
        </a>

        <div id="pages">
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('profile.user')}}">
                    Profile
                </a>
            {% else %}
                <a href="{{ url_for('auth.register')}}">
                    Profile
                </a>
            {% endif %}

            <a href="{{ url_for('posts.popular')}}">
                Popular
            </a>

            <a href="{{ url_for('main.about')}}">
                About
            </a>
        </div>

        
        
        {% if current_user.is_authenticated %}
            <button name="{{ current_user.id }}" onclick="logout()">Logout</button>
            <button onclick="window.location.href = '/add-post'">Create</button>
            <script>
                async function logout() {
                    try {
                        const response = await fetch("/logout", { 
                            method: "POST",
                        });
                        if (response.ok) {
                            window.location.href = "/"; 
                        } else {
                            console.error("Logout failed");
                        }
                    } catch (error) {
                        console.error("Error during logout:", error);
                    }
                }
            </script>
        {% else %}
            <button onclick="window.location.href = `{{ url_for('auth.login') }}`">Log in</button>
            <button onclick="window.location.href = `{{ url_for('auth.register') }}`">Sign up</button>
        {% endif %}
    </div>
</header>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arteria</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/welcome.css')}}">
    <meta name="author" content="feredeyz">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='styles/images/arteria-logo.png') }}">

</head>
<body>
    {% include "header.html" %}

    <div id="center-text">
        <p id="welcome-text">WELCOME</p>
        <p id="to-text">TO</p>
        <div id="arteria-list">
            <p id="a1">ARTERIA</p>
            <p id="a2">ARTERIA</p>
            <p id="a3">ARTERIA</p>
            <p id="a4">ARTERIA</p>
            <p id="a5">ARTERIA</p>
            <p id="a6">ARTERIA</p>
            <p id="a7">ARTERIA</p>
        </div>
    </div>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='styles/images/arteria-logo.png') }}">

    <title>Arteria: Log in</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/login.css') }}">
</head>
<body>
    {% include "header.html" %}
    <div id="login-form">
        <h1 id="title">Logging in</h1>
        <form action="/login" method="post">
            {{ form.csrf_token }}
            {{ form.username.label }} {{ form.username }} <br>
            {{ form.password.label }} {{ form.password }} <br>
            {{ form.submit }}
        </form>
        <p id="error" style="display: none;">{{ error }}</p>
        {% if error %}
            <script>
                const error = document.getElementById('error').innerHTML;
                alert(error);
            </script>
        {% endif %}
    </div>
</body>
</html>

app/templates/popular.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Arteria: Popular</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/popular.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='styles/images/arteria-logo.png') }}">
</head>
<body>
    {% include "header.html" %}

    <div id="posts">

        <ul>
            {% for post in posts %} 
                <li>
                    <div class="post">
                        <div class="post-user">
                            <img class="post-avatar" src="{{ url_for('static', filename=(post.user.avatar or 'styles/images/user-profile-pic.jpg')) }}" alt="avatar">
                            <p>{{ post.user.username }}</p>
                        </div>
                        <div class="post-text">     
                            <h1 class="post-title" style="display: inline;">{{ post.title }}</h1> 
                            <p class="post-date" style="display: inline;">({{ post.created_at }})</p>
                            <textarea name="{{ post.id }}" readonly class="post-content">{{ post.content }}</textarea>
                            {% if current_user.id in post.liked_by | map(attribute='id') | list %}
                                <button class="addlike" id="{{ post.id }}" name="{{ current_user.id }}" onclick="deleteLike(this)">
                                    <img id="heart" src="{{ url_for('static', filename='styles/images/heart.png') }}" alt="Likes">
                                    <span>{{ post.likes }}</span> 
                                </button>
                            {% else %}
                                <button class="addlike" id="{{ post.id }}" name="{{ current_user.id }}" onclick="addLike(this)">
                                    <img id="heart" src="{{ url_for('static', filename='styles/images/heart_gray.png') }}" alt="Likes">
                                    <span>{{ post.likes }}</span> 
                                </button>
                            {% endif %}


                            
                        </div>
                        {% if current_user.id == post.user.id %}
                            <div id="post-buttons">
                                <button id="edit-post-button" onclick="editPost(this)" name="{{ post.id }}"><img src="{{url_for('static', filename='styles/images/edit.png')}}" alt="Edit"></button>
                                <button id="delete-post-button" onclick="deletePost(this)" name="{{ post.id }}"><img src="{{url_for('static', filename='styles/images/bin.png')}}" alt="Edit"></button>
                                
                            </div>
                        {% endif %}
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>

    <script src="{{ url_for('static', filename='js/popular.js') }}"></script>
</body>
</html>

app/templates/registrate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='styles/images/arteria-logo.png') }}">

    <title>Arteria: Registration</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/registration.css') }}">
</head>
<body>
    {% include "header.html" %}
    <div id="reg-form">
        <h1 id="title">Singing up</h1>
        <form action="/register" method="post">
            {{ form.hidden_tag() }}
            {{ form.username.label }} {{ form.username() }}<br>
            {{ form.password.label }} {{ form.password() }}<br>
            {{ form.verify_password.label }} {{ form.verify_password() }}<br>
            {{ form.submit() }}
        </form>
        <p id="error" style="display: none;">{{ error }}</p>
        {% if error %}
            <script>
                const error = document.getElementById('error').innerHTML;
                alert(error);
            </script>
        {% endif %}
    </div>
</body>
</html>

app/templates/user-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{url_for('static', filename='styles/user_profile.css')}}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='styles/images/arteria-logo.png') }}">

    <title>Arteria: {{ current_user.username }}</title>
</head>
<body>
    {% include "header.html" %}
    <div id="about-user">
        <div id="picture">
            <img id="user-profile-pic" src="{{ url_for('static', filename=(current_user.avatar or 'styles/images/user-profile-pic.jpg')) }}" alt="avatar">
            <button onclick="document.getElementsByClassName('avatarFile')[0].click()"><img src="{{url_for('static', filename='styles/images/edit.png')}}" alt="Edit"></button>
            <input id="{{ current_user.id }}" name="image" accept="image/png, image/jpeg" type="file" style="display: none;" class="avatarFile" oninput="changeAvatar(this)">
        </div>
        <div>
            <textarea id="username">{{current_user.username}}</textarea>
            <p id="date">{{current_user.date}}</p>
            <textarea id="desc-text" placeholder="Click to edit description">{{ current_user.description or "" }}</textarea>
            <button onclick="confirmEditting(this)" name="{{ current_user.id }}" id="confirm-button"><img src="{{ url_for('static', filename='styles/images/check.png')}}" alt="Confirm Edditing"></button>
        </div>
    </div>
    <script src="{{url_for('static', filename='js/userProfile.js')}}"></script>
</body>
</html>